FROM apache/airflow:2.7.1
USER root
RUN apt-get update && apt-get install -y \
    ffmpeg libsm6 \
    libxext6 \
    poppler-utils \
    tesseract-ocr \
    libtesseract-dev \
    libleptonica-dev \
    tesseract-ocr-por \
    myspell-pt-br \
    enchant-2
    
USER airflow
COPY requirements.txt .
RUN pip install -r requirements.txt