digest: e0e30213
name: dataset
profile: '{"num_rows": 1396, "num_elements": 1396}'
schema: '{"mlflow_colspec": [{"type": "string", "name": "text"}]}'
source: '{"tags": {"mlflow.user": "airflow", "mlflow.source.name": "/home/airflow/.local/bin/airflow",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
