digest: 9f1c5a57
name: dataset
profile: '{"num_rows": 697, "num_elements": 697}'
schema: '{"mlflow_colspec": [{"type": "string", "name": "text"}]}'
source: '{"tags": {"mlflow.user": "airflow", "mlflow.source.name": "/home/airflow/.local/bin/airflow",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
